/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2021-07-11 19:37:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/home/ubuntu/apache-tomcat-9.0.50/webapps/vprofile-v1/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153385082000L));
    _jspx_dependants.put("jar:file:/home/ubuntu/apache-tomcat-9.0.50/webapps/vprofile-v1/WEB-INF/lib/spring-webmvc-4.2.0.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1438306582000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1626026436000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.2.0.RELEASE.jar", Long.valueOf(1626026434000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <title>Welcome</title>\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/profile.css\" rel=\"stylesheet\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://bootswatch.com/cosmo/bootstrap.min.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"mainbody container-fluid\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"navbar-wrapper\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <div class=\"navbar navbar-custom navbar-static-top\" role=\"navigation\">\n");
      out.write("                    <div class=\"container-fluid\">\n");
      out.write("                        <div class=\"navbar-header\">\n");
      out.write("                            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("                                <span class=\"sr-only\">Toggle navigation</span> <span class=\"icon-bar\"></span><span\n");
      out.write("                                    class=\"icon-bar\"></span><span class=\"icon-bar\"></span>\n");
      out.write("                            </button>\n");
      out.write("                            <a class=\"navbar-brand\" href=\"#\" style=\"margin-right:-8px; margin-top:-5px;\">\n");
      out.write("                                <img alt=\"Brand\" src=\"https://lut.im/7trApsDX08/GeilMRp1FIm4f2p7.png\" width=\"30px\" height=\"30px\">\n");
      out.write("                            </a>\n");
      out.write("                            <a class=\"navbar-brand\" href=\"#\">VisualPath</a>\n");
      out.write("                            <i class=\"brand_network\"><small><small>VP* Network</small></small></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"navbar-collapse collapse\">\n");
      out.write("                            <ul class=\"nav navbar-nav\">\n");
      out.write("                                <li><a href=\"./ORqmj\">Stream</a></li>\n");
      out.write("                                <li><a href=\"#\">My Activity</a></li>\n");
      out.write("                                <li><span class=\"badge badge-important\">2</span><a href=\"#\"><i class=\"fa fa-bell-o fa-lg\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-envelope-o fa-lg\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("                            </ul>\n");
      out.write("                            <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                                <li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                                    <span class=\"user-avatar pull-left\" style=\"margin-right:8px; margin-top:-5px;\">\n");
      out.write("                                        <img src=\"https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png\" class=\"img-responsive img-circle\" title=\"John Doe\" alt=\"John Doe\" width=\"30px\" height=\"30px\">\n");
      out.write("                                    </span>\n");
      out.write("                                    <span class=\"user-name\">\n");
      out.write("                                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                                    </span>\n");
      out.write("                                    <b class=\"caret\"></b></a>\n");
      out.write("                                    <ul class=\"dropdown-menu\">\n");
      out.write("                                        <li>\n");
      out.write("                                            <div class=\"navbar-content\">\n");
      out.write("                                                <div class=\"row\">\n");
      out.write("                                                    <div class=\"col-md-5\">\n");
      out.write("                                                        <img src=\"https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png\" alt=\"Alternate Text\" class=\"img-responsive\" width=\"120px\" height=\"120px\" />\n");
      out.write("                                                        <p class=\"text-center small\">\n");
      out.write("                                                            <a href=\"./3X6zm\">Change Photo</a></p>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <div class=\"col-md-7\">\n");
      out.write("                                                        <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> <br/>\n");
      out.write("                                                        <p class=\"text-muted small\">\n");
      out.write("                                                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("@visualpath.co.in</p>\n");
      out.write("                                                        <div class=\"divider\">\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <a href=\"./56ExR\" class=\"btn btn-default btn-xs\"><i class=\"fa fa-user-o\" aria-hidden=\"true\"></i> Profile</a>\n");
      out.write("                                                        <a href=\"#\" class=\"btn btn-default btn-xs\"><i class=\"fa fa-address-card-o\" aria-hidden=\"true\"></i> Contacts</a>\n");
      out.write("                                                        <a href=\"#\" class=\"btn btn-default btn-xs\"><i class=\"fa fa-cogs\" aria-hidden=\"true\"></i> Settings</a>\n");
      out.write("                                                        <a href=\"#\" class=\"btn btn-default btn-xs\"><i class=\"fa fa-question-circle-o\" aria-hidden=\"true\"></i> Help!</a>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"navbar-footer\">\n");
      out.write("                                                <div class=\"navbar-footer-content\">\n");
      out.write("                                                    <div class=\"row\">\n");
      out.write("                                                        <div class=\"col-md-6\">\n");
      out.write("                                                            <a href=\"#\" class=\"btn btn-default btn-sm\"><i class=\"fa fa-unlock-alt\" aria-hidden=\"true\"></i> Change Passowrd</a>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-md-6\">\n");
      out.write("                                                            <a onclick=\"document.forms['logoutForm'].submit()\" class=\"btn btn-default btn-sm pull-right\"><i class=\"fa fa-power-off\" aria-hidden=\"true\"></i> Sign Out</a>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div style=\"padding-top:50px;\">.</div>\n");
      out.write("        <div class=\"col-lg-3 col-md-3 hidden-sm hidden-xs\">\n");
      out.write("            <div class=\"panel panel-default\">\n");
      out.write("                <div class=\"panel-body\">\n");
      out.write("                    <div class=\"media\">\n");
      out.write("                        <div align=\"center\">\n");
      out.write("                            <img class=\"thumbnail img-responsive\" src=\"https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png\" width=\"300px\" height=\"300px\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"media-body\">\n");
      out.write("                            <hr>\n");
      out.write("                            <h3><strong>Bio</strong></h3>\n");
      out.write("                            <p>DevOps For Product Management and Strategy of Application Delivery at VisualPath Technologies. Responsible of providing customers with counsel on their DevOps strategies to help them deliver higher quality software and services to market faster.</p>\n");
      out.write("                            <hr>\n");
      out.write("                            <h3><strong>Location</strong></h3>\n");
      out.write("                            <p>Earth</p>\n");
      out.write("                            <hr>\n");
      out.write("                            <h3><strong>Gender</strong></h3>\n");
      out.write("                            <p>Unknown</p>\n");
      out.write("                            <hr>\n");
      out.write("                            <h3><strong>Birthday</strong></h3>\n");
      out.write("                            <p>January 01 1901</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-lg-9 col-md-9 col-sm-12 col-xs-12\">\n");
      out.write("            <div class=\"panel panel-default\">\n");
      out.write("                <div class=\"panel-body\">\n");
      out.write("                    <span>\n");
      out.write("                        <h1 class=\"panel-title pull-left\" style=\"font-size:30px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" &nbsp; <small>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("@visualpath.co.in</small> <i class=\"fa fa-check text-success\" aria-hidden=\"true\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\" sharing with you\"></i></h1>\n");
      out.write("                        <div class=\"dropdown pull-right\">\n");
      out.write("                            <button class=\"btn btn-success dropdown-toggle\" type=\"button\" id=\"dropdownMenu1\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">\n");
      out.write("                                Friends\n");
      out.write("                                <span class=\"caret\"></span>\n");
      out.write("                            </button>\n");
      out.write("                            <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenu1\">\n");
      out.write("                                <li><a href=\"#\">Familly</a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-fw fa-check\" aria-hidden=\"true\"></i> Friends</a></li>\n");
      out.write("                                <li><a href=\"#\">Work</a></li>\n");
      out.write("                                <li role=\"separator\" class=\"divider\"></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-fw fa-plus\" aria-hidden=\"true\"></i> Add a new aspect</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </span>\n");
      out.write("                    <br><br>\n");
      out.write("                    <i class=\"fa fa-tags\" aria-hidden=\"true\"></i> <a href=\"#\" class=\"tag\">#DevOps</a> <a href=\"#\" class=\"tag\"> #Continuous Integration</a> <a href=\"#\" class=\"tag\"> #Continuous Delivery </a><a href=\"#\" class=\"tag\"> #Automation</a>\n");
      out.write("                    <br><br><hr>\n");
      out.write("                    <span class=\"pull-left\">\n");
      out.write("                        <a href=\"#\" class=\"btn btn-link\" style=\"text-decoration:none;\"><i class=\"fa fa-fw fa-files-o\" aria-hidden=\"true\"></i> Posts</a>\n");
      out.write("                        <a href=\"#\" class=\"btn btn-link\" style=\"text-decoration:none;\"><i class=\"fa fa-fw fa-picture-o\" aria-hidden=\"true\"></i> Photos <span class=\"badge\">42</span></a>\n");
      out.write("                        <a href=\"#\" class=\"btn btn-link\" style=\"text-decoration:none;\"><i class=\"fa fa-fw fa-users\" aria-hidden=\"true\"></i> Contacts <span class=\"badge\">42</span></a>\n");
      out.write("                    </span>\n");
      out.write("                    <span class=\"pull-right\">\n");
      out.write("                        <a href=\"#\" class=\"btn btn-link\" style=\"text-decoration:none;\"><i class=\"fa fa-lg fa-at\" aria-hidden=\"true\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Mention\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"btn btn-link\" style=\"text-decoration:none;\"><i class=\"fa fa-lg fa-envelope-o\" aria-hidden=\"true\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Message\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"btn btn-link\" style=\"text-decoration:none;\"><i class=\"fa fa-lg fa-ban\" aria-hidden=\"true\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Ignore\"></i></a>\n");
      out.write("                    </span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <hr>\n");
      out.write("            <!-- Simple post content example. -->\n");
      out.write("            <div class=\"panel panel-default\">\n");
      out.write("                <div class=\"panel-body\">\n");
      out.write("                    <div class=\"pull-left\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <img class=\"media-object img-circle\" src=\"https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png\" width=\"50px\" height=\"50px\" style=\"margin-right:8px; margin-top:-5px;\">\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                    <h4><a href=\"#\" style=\"text-decoration:none;\"><strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong></a><small><small><a href=\"#\" style=\"text-decoration:none; color:grey;\"><i><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> 42 minutes ago</i></a></small></small></h4>\n");
      out.write("                    <span>\n");
      out.write("                        <div class=\"navbar-right\">\n");
      out.write("                            <div class=\"dropdown\">\n");
      out.write("                                <button class=\"btn btn-link btn-xs dropdown-toggle\" type=\"button\" id=\"dd1\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">\n");
      out.write("                                    <i class=\"fa fa-cog\" aria-hidden=\"true\"></i>\n");
      out.write("                                    <span class=\"caret\"></span>\n");
      out.write("                                </button>\n");
      out.write("                                <ul class=\"dropdown-menu\" aria-labelledby=\"dd1\" style=\"float: right;\">\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-exclamation-triangle\" aria-hidden=\"true\"></i> Report</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-ban\" aria-hidden=\"true\"></i> Ignore</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-bell\" aria-hidden=\"true\"></i> Enable notifications for this post</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-eye-slash\" aria-hidden=\"true\"></i> Hide</a></li>\n");
      out.write("                                    <li role=\"separator\" class=\"divider\"></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-trash\" aria-hidden=\"true\"></i> Delete</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </span>\n");
      out.write("                    <hr>\n");
      out.write("                    <div class=\"post-content\">\n");
      out.write("                        <p>\"The Key to DevOps Success.\"</p>\n");
      out.write("                        <p>The Key to DevOps Success\" Collaboration\". Collaboration is essential to DevOps,yet how to do it is often unclear with many teams falling back on ineffective conference calls, instant messaging, documents, and SharePoint sites. In this keynote,we will share a vision for a next generation DevOps where collaboration, continuous documentation, and knowledge capture are combined with automation toolchains to enable rapid innovation and deployment.</p>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"pull-right btn-group-xs\">\n");
      out.write("                            <a class=\"btn btn-default btn-xs\"><i class=\"fa fa-heart\" aria-hidden=\"true\"></i> Like</a>\n");
      out.write("                            <a class=\"btn btn-default btn-xs\"><i class=\"fa fa-retweet\" aria-hidden=\"true\"></i> Reshare</a>\n");
      out.write("                            <a class=\"btn btn-default btn-xs\"><i class=\"fa fa-comment\" aria-hidden=\"true\"></i> Comment</a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"pull-left\">\n");
      out.write("                            <p class=\"text-muted\" style=\"margin-left:5px;\"><i class=\"fa fa-globe\" aria-hidden=\"true\"></i> Public</p>\n");
      out.write("                        </div>\n");
      out.write("                        <br>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <div class=\"media\">\n");
      out.write("                        <div class=\"pull-left\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img class=\"media-object img-circle\" src=\"https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png\" width=\"35px\" height=\"35px\" style=\"margin-left:3px; margin-right:-5px;\">\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"media-body\">\n");
      out.write("                            <textarea class=\"form-control\" rows=\"1\" placeholder=\"Comment\"></textarea>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Reshare Example -->\n");
      out.write("            <div class=\"panel panel-default\">\n");
      out.write("                <div class=\"panel-body\">\n");
      out.write("                    <div class=\"pull-left\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <img class=\"media-object img-circle\" src=\"https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png\" width=\"50px\" height=\"50px\" style=\"margin-right:8px; margin-top:-5px;\">\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                    <h4><a href=\"#\" style=\"text-decoration:none;\"><strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong></a><small><small><a href=\"#\" style=\"text-decoration:none; color:grey;\"><i><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> 42 minutes ago</i></a></small></small></h4>\n");
      out.write("                    <span>\n");
      out.write("                        <div class=\"navbar-right\">\n");
      out.write("                            <div class=\"dropdown\">\n");
      out.write("                                <button class=\"btn btn-link btn-xs dropdown-toggle\" type=\"button\" id=\"dd1\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">\n");
      out.write("                                    <i class=\"fa fa-cog\" aria-hidden=\"true\"></i>\n");
      out.write("                                    <span class=\"caret\"></span>\n");
      out.write("                                </button>\n");
      out.write("                                <ul class=\"dropdown-menu\" aria-labelledby=\"dd1\" style=\"float: right;\">\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-exclamation-triangle\" aria-hidden=\"true\"></i> Report</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-ban\" aria-hidden=\"true\"></i> Ignore</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-bell\" aria-hidden=\"true\"></i> Enable notifications for this post</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-eye-slash\" aria-hidden=\"true\"></i> Hide</a></li>\n");
      out.write("                                    <li role=\"separator\" class=\"divider\"></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-trash\" aria-hidden=\"true\"></i> Delete</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </span>\n");
      out.write("                    <hr>\n");
      out.write("                    <div class=\"post-content\">\n");
      out.write("                        <div class=\"panel panel-default\">\n");
      out.write("                            <div class=\"panel-body\">\n");
      out.write("                                <div class=\"pull-left\">\n");
      out.write("                                    <a href=\"#\">\n");
      out.write("                                        <img class=\"media-object img-circle\" src=\"https://diaspote.org/uploads/images/thumb_large_283df6397c4db3fe0344.png\" width=\"50px\" height=\"50px\" style=\"margin-right:8px; margin-top:-5px;\">\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                                <h4><a href=\"#\" style=\"text-decoration:none;\"><strong>Waheed Khan</strong></a> <small><small><a href=\"#\" style=\"text-decoration:none; color:grey;\"><i><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> about 10 hours ago</i></a></small></small></h4>\n");
      out.write("                                <hr>\n");
      out.write("                                <div class=\"post-content\">\n");
      out.write("                                     <p>What are DevOps skills?</p>\n");
      out.write("                                    <p>Our respondents identified the top three skill areas for DevOps staff:</p>\n");
      out.write("                                    <p>1) Coding or scripting 2)Process re-engineering 3)Communicating and collaborating with others Extensive knowledge of software build cycles 4)Experience deploying code 5)Experience in software architecture 6)Familiarity with application programming 7)Database management 8)System design.</p>\n");
      out.write("									<p>These skills all point to a growing recognition that software is not written in the old way anymore. Where software used to be written from scratch in a highly complex and lengthy process, creating new products is now often a matter of choosing open source components and stitching them together with code. The complexity of todays software lies less in the authoring, and more in ensuring that the new software will work across a diverse set of operating systems and platforms right away. Likewise, testing and deployment are now done much more frequently. That is, they can be more frequent,if developers communicate early and regularly with the operations team, and if ops people bring their knowledge of the production environment to design of testing and staging environments.</p>                                \n");
      out.write("                                    <p>Demand for people with DevOps skills is growing rapidly because businesses get great results from DevOps. Organizations using DevOps practices are overwhelmingly high-functioning: They deploy code up to 30 times more frequently than their competitors.</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"pull-right btn-group-xs\">\n");
      out.write("                            <a class=\"btn btn-default btn-xs\"><i class=\"fa fa-heart\" aria-hidden=\"true\"></i> Like</a>\n");
      out.write("                            <a class=\"btn btn-default btn-xs\"><i class=\"fa fa-retweet\" aria-hidden=\"true\"></i> Reshare</a>\n");
      out.write("                            <a class=\"btn btn-default btn-xs\"><i class=\"fa fa-comment\" aria-hidden=\"true\"></i> Comment</a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"pull-left\">\n");
      out.write("                            <p class=\"text-muted\" style=\"margin-left:5px;\"><i class=\"fa fa-globe\" aria-hidden=\"true\"></i> Public</p>\n");
      out.write("                        </div>\n");
      out.write("                        <br>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <div class=\"media\">\n");
      out.write("                        <div class=\"pull-left\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img class=\"media-object img-circle\" src=\"https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png\" width=\"35px\" height=\"35px\" style=\"margin-left:3px; margin-right:-5px;\">\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"media-body\">\n");
      out.write("                            <textarea class=\"form-control\" rows=\"1\" placeholder=\"Comment\"></textarea>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Sample post content with picture. -->\n");
      out.write("            <div class=\"panel panel-default\">\n");
      out.write("                <div class=\"panel-body\">\n");
      out.write("                    <div class=\"pull-left\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <img class=\"media-object img-circle\" src=\"https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png\" width=\"50px\" height=\"50px\" style=\"margin-right:8px; margin-top:-5px;\">\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                    <h4><a href=\"#\" style=\"text-decoration:none;\"><strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong></a><small><small><a href=\"#\" style=\"text-decoration:none; color:grey;\"><i><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> 42 minutes ago</i></a></small></small></h4>\n");
      out.write("                    <span>\n");
      out.write("                        <div class=\"navbar-right\">\n");
      out.write("                            <div class=\"dropdown\">\n");
      out.write("                                <button class=\"btn btn-link btn-xs dropdown-toggle\" type=\"button\" id=\"dd1\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">\n");
      out.write("                                    <i class=\"fa fa-cog\" aria-hidden=\"true\"></i>\n");
      out.write("                                    <span class=\"caret\"></span>\n");
      out.write("                                </button>\n");
      out.write("                                <ul class=\"dropdown-menu\" aria-labelledby=\"dd1\" style=\"float: right;\">\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-exclamation-triangle\" aria-hidden=\"true\"></i> Report</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-ban\" aria-hidden=\"true\"></i> Ignore</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-bell\" aria-hidden=\"true\"></i> Enable notifications for this post</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-eye-slash\" aria-hidden=\"true\"></i> Hide</a></li>\n");
      out.write("                                    <li role=\"separator\" class=\"divider\"></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-trash\" aria-hidden=\"true\"></i> Delete</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </span>\n");
      out.write("                    <hr>\n");
      out.write("                    <div class=\"post-content\">\n");
      out.write("                        <p>\" Manager Reaction On Your Work without DevOps \"</p>\n");
      out.write("                        <img class=\"img-responsive\" src=\"https://media.giphy.com/media/j1QQj6To9Pbxu/giphy.gif\">\n");
      out.write("                        <p><br><a href=\"#\" class=\"tag\">#  I want DevOps </a> <a href=\"#\" class=\"tag\">#  DevOps..</a></p>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"pull-right btn-group-xs\">\n");
      out.write("                            <a class=\"btn btn-default btn-xs\"><i class=\"fa fa-heart\" aria-hidden=\"true\"></i> Like</a>\n");
      out.write("                            <a class=\"btn btn-default btn-xs\"><i class=\"fa fa-retweet\" aria-hidden=\"true\"></i> Reshare</a>\n");
      out.write("                            <a class=\"btn btn-default btn-xs\"><i class=\"fa fa-comment\" aria-hidden=\"true\"></i> Comment</a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"pull-left\">\n");
      out.write("                            <p class=\"text-muted\" style=\"margin-left:5px;\"><i class=\"fa fa-globe\" aria-hidden=\"true\"></i> Public <strong>via mobile</strong></p>\n");
      out.write("                        </div>\n");
      out.write("                        <br>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <div class=\"media\">\n");
      out.write("                        <div class=\"pull-left\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img class=\"media-object img-circle\" src=\"https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png\" width=\"35px\" height=\"35px\" style=\"margin-left:3px; margin-right:-5px;\">\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"media-body\">\n");
      out.write("                            <textarea class=\"form-control\" rows=\"1\" placeholder=\"Comment\"></textarea>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Sample post content with comments. -->\n");
      out.write("            <div class=\"panel panel-default\">\n");
      out.write("                <div class=\"panel-body\">\n");
      out.write("                    <div class=\"pull-left\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <img class=\"media-object img-circle\" src=\"https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png\" width=\"50px\" height=\"50px\" style=\"margin-right:8px; margin-top:-5px;\">\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                    <h4><a href=\"#\" style=\"text-decoration:none;\"><strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong></a> <small><small><a href=\"#\" style=\"text-decoration:none; color:grey;\"><i><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> 42 minutes ago</i></a></small></small></h4>\n");
      out.write("                    <span>\n");
      out.write("                        <div class=\"navbar-right\">\n");
      out.write("                            <div class=\"dropdown\">\n");
      out.write("                                <button class=\"btn btn-link btn-xs dropdown-toggle\" type=\"button\" id=\"dd1\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">\n");
      out.write("                                    <i class=\"fa fa-cog\" aria-hidden=\"true\"></i>\n");
      out.write("                                    <span class=\"caret\"></span>\n");
      out.write("                                </button>\n");
      out.write("                                <ul class=\"dropdown-menu\" aria-labelledby=\"dd1\" style=\"float: right;\">\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-exclamation-triangle\" aria-hidden=\"true\"></i> Report</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-ban\" aria-hidden=\"true\"></i> Ignore</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-bell\" aria-hidden=\"true\"></i> Enable notifications for this post</a></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-eye-slash\" aria-hidden=\"true\"></i> Hide</a></li>\n");
      out.write("                                    <li role=\"separator\" class=\"divider\"></li>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-fw fa-trash\" aria-hidden=\"true\"></i> Delete</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </span>\n");
      out.write("                    <hr>\n");
      out.write("                    <div class=\"post-content\">\n");
      out.write("                        <p>\"Feeling Happy to be a DevOps.\"</p>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"pull-right btn-group-xs\">\n");
      out.write("                            <a class=\"btn btn-default btn-xs\"><i class=\"fa fa-heart\" aria-hidden=\"true\"></i> Like</a>\n");
      out.write("                            <a class=\"btn btn-default btn-xs\"><i class=\"fa fa-comment\" aria-hidden=\"true\"></i> Comment</a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"pull-left\">\n");
      out.write("                            <p class=\"text-muted\" style=\"margin-left:5px;\"><i class=\"fa fa-user-secret\" aria-hidden=\"true\"></i> Limited</p>\n");
      out.write("                        </div>\n");
      out.write("                        <br>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <div>\n");
      out.write("                        <a class=\"btn btn-default btn-xs\"><i class=\"fa fa-bars\" aria-hidden=\"true\"></i> Show 12 more comments</a>\n");
      out.write("                        <hr>\n");
      out.write("                        <div class=\"post-content\">\n");
      out.write("                            <div class=\"panel-default\">\n");
      out.write("                                <div class=\"panel-body\">\n");
      out.write("                                    <div class=\"pull-left\">\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <img class=\"media-object img-circle\" src=\"https://diaspote.org/uploads/images/thumb_large_283df6397c4db3fe0344.png\" width=\"35px\" height=\"35px\" style=\"margin-right:8px; margin-top:-5px;\">\n");
      out.write("                                        </a>\n");
      out.write("                                    </div>\n");
      out.write("                                    <h4><a href=\"#\" style=\"text-decoration:none;\"><strong>Kiran Kumar</strong></a></h4>\n");
      out.write("                                    <hr>\n");
      out.write("                                    <div class=\"post-content\">\n");
      out.write("                                        <p>DevOps has significant importance to any company delivering software or technical services today.Defining DevOps is trickier than you would think, primarily because of its wide usage. It is essentially shorthand, and nothing more than that, for a lean approach to software delivery.</p>\n");
      out.write("                                        <br><small><small><a href=\"#\" style=\"text-decoration:none; color:grey;\"><i><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> 12 minutes ago</i></a></small></small>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <hr>\n");
      out.write("                        <div class=\"post-content\">\n");
      out.write("                            <div class=\"panel-default\">\n");
      out.write("                                <div class=\"panel-body\">\n");
      out.write("                                    <div class=\"pull-left\">\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <img class=\"media-object img-circle\" src=\"https://lut.im/yR07xwobAA/bZpvdTZmBBTZDJDd.png\" width=\"35px\" height=\"35px\" style=\"margin-right:8px; margin-top:-5px;\">\n");
      out.write("                                        </a>\n");
      out.write("                                    </div>\n");
      out.write("                                    <h4><a href=\"#\" style=\"text-decoration:none;\"><strong>Mi Chleen</strong></a></h4>\n");
      out.write("                                    <hr>\n");
      out.write("                                    <div class=\"post-content\">\n");
      out.write("                                        <p>The secret to DevOps maturity is not technology or process, but people. It takes engaged leadership and all for one cooperation to achieve the kind of results that lead companies to superior IT performance. High-performing DevOps teams can recover 168 times faster from failures and have 60 times fewer failures due to changes, according to the 2015 State of DevOps Report by Puppet Labs. High-performing teams also release code at significantly increasing velocity as their teams grow in size, approaching three deploys per day per developer, for teams of around 1000 developers.</p>\n");
      out.write("                                        <br><small><small><a href=\"#\" style=\"text-decoration:none; color:grey;\"><i><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> 9 minutes ago</i></a></small></small>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <hr>\n");
      out.write("                        <div class=\"post-content\">\n");
      out.write("                            <div class=\"panel-default\">\n");
      out.write("                                <div class=\"panel-body\">\n");
      out.write("                                    <div class=\"pull-left\">\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <img class=\"media-object img-circle\" src=\"https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png\" width=\"35px\" height=\"35px\" style=\"margin-right:8px; margin-top:-5px;\">\n");
      out.write("                                        </a>\n");
      out.write("                                    </div>\n");
      out.write("                                    <h4><a href=\"#\" style=\"text-decoration:none;\"><strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong></a></h4>\n");
      out.write("                                    <hr>\n");
      out.write("                                    <div class=\"post-content\">\n");
      out.write("                                        <p>At a time when the speed of application development is vital to commercial success, the DevOps methodology based on communication, collaboration, integration and automation has become one of the biggest IT moves around. However, it is more than just a business philosophy;to do it right requires genuine infrastructure investment and development.</p>\n");
      out.write("                                        <br><small><small><a href=\"#\" style=\"text-decoration:none; color:grey;\"><i><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> 2 minutes ago</i></a></small></small>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"media\">\n");
      out.write("                        <div class=\"pull-left\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img class=\"media-object img-circle\" src=\"https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png\" width=\"35px\" height=\"35px\" style=\"margin-left:3px; margin-right:-5px;\">\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"media-body\">\n");
      out.write("                            <textarea class=\"form-control\" rows=\"1\" placeholder=\"Comment\"></textarea>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<div class=\"container\">\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</div>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(function () {\n");
      out.write("	  $('[data-toggle=\"tooltip\"]').tooltip()\n");
      out.write("	})\n");
      out.write("	$(function () {\n");
      out.write("	  $('[data-toggle=\"popover\"]').popover()\n");
      out.write("	})\n");
      out.write("</script>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/welcome.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/welcome.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/welcome.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/welcome.jsp(458,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        <form id=\"logoutForm\" method=\"POST\" action=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logout\">\n");
          out.write("            <input type=\"hidden\" name=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\n");
          out.write("        </form>\n");
          out.write("\n");
          out.write("        <h2>Welcome ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" | <a onclick=\"document.forms['logoutForm'].submit()\">Logout</a></h2>\n");
          out.write("\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
